[project]
name = 'Decentralized-Trade-Documentation-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.customs-compliance]
path = 'contracts/customs-compliance.clar'
clarity_version = 2
epoch = 2.5

[contracts.docunent-certificaiton]
path = 'contracts/docunent-certificaiton.clar'
clarity_version = 2
epoch = 2.5

[contracts.exporter-verification]
path = 'contracts/exporter-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.payment-authorization]
path = 'contracts/payment-authorization.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
